// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjvShSMZXm4LUrLd6HC301OSLdMwc7kp0',
    appId: '1:137900084172:web:5371ce2279e998b0816b69',
    messagingSenderId: '137900084172',
    projectId: 'shieldpass-b7700',
    authDomain: 'shieldpass-b7700.firebaseapp.com',
    storageBucket: 'shieldpass-b7700.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDou0UdLD-domFDkGtX6JC-0CefRzr0m_k',
    appId: '1:137900084172:android:29dcda491debd503816b69',
    messagingSenderId: '137900084172',
    projectId: 'shieldpass-b7700',
    storageBucket: 'shieldpass-b7700.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ZhwJm5JNlwyJFlbOBaz9I5wJjMITwMw',
    appId: '1:137900084172:ios:8176bde383ab6d6a816b69',
    messagingSenderId: '137900084172',
    projectId: 'shieldpass-b7700',
    storageBucket: 'shieldpass-b7700.appspot.com',
    androidClientId: '137900084172-5qnk1f2sb9p4uoq54nbujeib9b0d4nh4.apps.googleusercontent.com',
    iosClientId: '137900084172-ea43ls8gbl7348l8ua2t9jp1blfen38q.apps.googleusercontent.com',
    iosBundleId: 'cho.baldomero.ptf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ZhwJm5JNlwyJFlbOBaz9I5wJjMITwMw',
    appId: '1:137900084172:ios:27c7b65fabb72200816b69',
    messagingSenderId: '137900084172',
    projectId: 'shieldpass-b7700',
    storageBucket: 'shieldpass-b7700.appspot.com',
    androidClientId: '137900084172-5qnk1f2sb9p4uoq54nbujeib9b0d4nh4.apps.googleusercontent.com',
    iosClientId: '137900084172-g96hro50h7rhqto09evpr58hb6c42l1r.apps.googleusercontent.com',
    iosBundleId: 'cho.baldomero.ptf.RunnerTests',
  );
}
